#@TYPE: Machine
#@NAME: MYD-AM62X
#@DESCRIPTION: Machine configuration for the MYIR MYD-AM62X board

require conf/machine/include/am62xx-rt.inc
require conf/machine/include/ti-extras.inc

KERNEL_DEVICETREE_PREFIX = " \
    myir/myd-am62x \
"

KERNEL_DEVICETREE = " \
    myir/myd-am62x-6254.dtb \
    myir/myd-am62x-lvds-j6.dtbo \
    myir/myd-am62x-lvds-j5.dtbo \
    myir/myd-am62x-dual-lvds.dtbo \
"


KERNEL_DEVICETREE:append = " \
    myir/myd-am62x-6254.dtb \
    myir/myd-am62x-lvds-j6.dtbo \
    myir/myd-am62x-lvds-j5.dtbo \
    myir/myd-am62x-dual-lvds.dtbo \
"

FIT_CONF_DEFAULT_DTB = "myir/myd-am62x-6254.dtb"

UBOOT_MACHINE = "myc_am62x_a53_emmc_defconfig"

# Override to use GP version of tiboot3 instead of default HS-FS
IMAGE_BOOT_FILES:remove = "tiboot3-am62x-hs-fs-evm.bin"
IMAGE_BOOT_FILES:prepend = "tiboot3-am62x-gp-evm.bin "

DEFAULT_TIMEZONE = "Asia/Shanghai"
